apiVersion: apps/v1
kind: Deployment
metadata:
  name: mf1
spec:
  selector:
    matchLabels:
      app: mf1
  template:
    metadata:
      labels:
        app: mf1
    spec:
      containers:
      - name: mf1
        image: localhost/mf1
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
